# Generated by Django 2.2.2 on 2019-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190625_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
